### PR TITLE
added support for bolt+routing scheme required for causal cluster and added retry in case of session expiry

### PR DESCRIPTION
**Pull request by mshekhar-mE**

### CODE REVIEW

**Comment by mshekhar-mE** [comment]
Hey, I haven't been able to prioritize working on routing contexts for causal cluster. If possible can you pls merge these changes.

**Comment by robinedwards** [comment]
Merged thank you

**Comment by akgoel-mo** [comment]
Thanks for merging @robinedwards. Can you also tag the latest master so that we can use routing url?

**Comment by robinedwards** [comment]
Sorry do you mean make a release? Cant you just pin to a commit in master?

**Comment by akgoel-mo** [comment]
Yes. I meant a release. Can you tell me how to pin to a commit in master?

**Comment by akgoel-mo** [comment]
Are you referring to this format - pip install git+git://github.com/robinedwards/neomodel.git@e7d2f70a09c27645711119679b73e18000c6212e

**Comment by akgoel-mo** [comment]
How can I specify this in setup.py of my package?

**Comment by robinedwards** [comment]
https://mike.zwobble.org/2013/05/adding-git-or-hg-or-svn-dependencies-in-setup-py/

**Comment by akgoel-mo** [comment]
@robinedwards This approach seems to have been deprecated and running a package install isn't installing neomodel. We are going by the requirements.txt approach for now.

**Pull request merged**
