### PR TITLE
Django settings

### PR DESCRIPTION
**Pull request by midnightlynx**
Added optional import of NEO4J_REST_URL through django.conf.settings.
If django is not installed and properly configured, or if NEO4J_REST_URL isn't defined in settings, it falls back to getting this value from the environment variable as before.

### CODE REVIEW

**Comment by nikbora** [comment]
Hey guys, I am curious why there is a need to add django dependencies to neomodel? Isn't neomodel meant to be standalone (e.g. we use it heavily from flask). 

Perhaps it would be better to have a django-neomodel plugin of some sort to deal with django specifics, a bit like you can get flask-sqlalchemy for sqlalchemy?

**Comment by robinedwards** [comment]
I agree with @nikbora, however this PR doesn't add it as a dependency as such, it would be nice to see specific modules for integration into the frameworks. Perhaps we should create a neomodel organisation and then flask_neomodel and django_neomodel can live under there?

**Comment by nikbora** [comment]
:+1: I agree this particular PR isn't too bad and is very guarded, but can see it being a precedent for more djangoey stuff in neomodel core hence the question :smile:

**Comment by midnightlynx** [comment]
I'm cool with helping with an integration module to do this instead. :) Maybe the support bits for django signals can be shifted there eventually as well.

**Comment by bleib1dj** [comment]
I concur. @robinedwards do you want to create the org?

**Comment by robinedwards** [comment]
@bleib1dj I've created the organisation, sorry for the delay away on vacation

**Comment by bleib1dj** [comment]
@robinedwards not a problem :). Thanks for setting it up!

**Comment by midnightlynx** [comment]
How do I find the org?

**Comment by bleib1dj** [comment]
https://github.com/neomodel

**Pull request closed without merging**
