### PR TITLE
Email and Regex properties

### PR DESCRIPTION
**Pull request by rafaelpivato**
Added some extra properties:
- `NormalProperty`
- `RegexProperty`
- `EmailProperty`

They are all based on `NormalProperty`, which serves as a base class for properties using the same method for either `inflate` or `deflate`.

### CODE REVIEW

**Comment by rafaelpivato** [comment]
Forgot to mention that we have `default_now` also for `DateTimeProperty` class.

**Comment by robinedwards** [comment]
Super thanks @rafaelpivato.

Some thoughts on this, not sure what the default_now offers that can't be achieved with datetime.now, the current method in neomodel follows django's convention which seems a bit more intuitive.

Regex property looks very useful though, I am a bit undecided if something such as an email field should live in this framework or a form library for example.

@bleib1dj what are your thoughts? As for normalproperty I think I'd like to keep a single common base class

**Comment by shayneoneill** [comment]
The normalize abstraction is excellent as a simple platform to build more complex types, as is the regex type

**Comment by robinedwards** [comment]
Thanks I've merged this in manually, sorry for the delay. If your still using neomodel and wish to help out please get in touch :-)

**Pull request closed without merging**
