### PR TITLE
added support for bolt+routing scheme required for causal cluster

### PR DESCRIPTION
**Pull request by mshekhar-mE**
Added support to accept bolt+routing as a valid scheme. This is required by causal cluster to redirect read/write requests to appropriate cluster members.
Routing support is enabled from neo4j-driver 1.2.1 and requires neo4j version to be 3.2 and up. Reference: https://neo4j.com/docs/developer-manual/3.2/drivers/client-applications/#_routing_drivers_with_routing_context

### CODE REVIEW

**Comment by mshekhar-mE** [comment]
Part of the changes planned for #257

**Comment by robinedwards** [comment]
Great dont we need to pass through the get params some how?

**Comment by akgoel-mo** [comment]
@robinedwards What get params are we referring to here? Are you referring to the routing context here? We didnt plan for a routing context here, but I guess it can be easily added. We will get the support for routing context added here as well.

**Comment by robinedwards** [comment]
Super yea I meant the routing context. Perhaps once its all done you could also add any relevant snippets of documentation just so people are aware neomodel supports it.

**Comment by robinedwards** [comment]
Hey thanks for the PR, would you mind removing the changes to setup.py I dont think they are intentional

**Comment by mshekhar-mE** [comment]
Hey, yeah those changes were meant for our internal use. It accidently got updated in this PR. I'm closing this PR and have raised another PR for similar changes [here (#264)](https://github.com/robinedwards/neomodel/pull/264).

**Pull request closed without merging**
