### PR TITLE
Add merge() method to nodes as update_or_insert()

### PR DESCRIPTION
**Pull request by andrefsp**
This commit adds the functionality of merge() nodes. The generated
cypher conforms with the MERGE query on neo4j.

http://neo4j.com/docs/stable/query-merge.html

This also tries to close issue #108

### CODE REVIEW

**Comment by bleib1dj** [comment]
@andrefsp Awesome, thanks for getting this in and sorry for the delay in a follow up. Could you please rebase to resolve the conflicts?

**Comment by andrefsp** [comment]
@bleib1dj Sure. I'll make sure all this is ready to go.  Is there anything needed for the docs ?

**Comment by bleib1dj** [comment]
We might want to add some explanation around the usage of the function and what it does to the docs. But let's hold off until @Hexadite-Max has completed the work discussed in #108 to see if there is any overlap and we have a better understanding of what docs are needed.

**Comment by andrefsp** [comment]
@bleib1dj  I've rebased the branches but had to do it on my account. Please follow the discussion on https://github.com/robinedwards/neomodel/pull/175 .

**Pull request closed without merging**
